### ISSUE TITLE
JT809.Inferior.Server 接收到的日期中“年”值不对

### ISSUE THREAD

**Issue by junjian-yuan** [SmallChi/JT809DotNetty#1]
![image](https://user-images.githubusercontent.com/10084420/57613592-d8478780-75a9-11e9-9ab5-bc46385c191a.png)

使用JT809.Inferior.Server 作为服务器
使用JT809.DotNetty.Tcp.Test 作为发送端

是我使用的不对吗？
或是哪里的问题？

**Comment by SmallChi** [comment]
这个线上已经解决了,最近比较忙没有时间更新809的,原因是年份解析成byte类型导致,其实是ushort类型

**Comment by wgms** [comment]
@SmallChi 这个项目还会更新吗，希望以后我有时间了可以参与其中

**Comment by SmallChi** [comment]
肯定会更新的，目前做了接收跟转发的，有时间就会搞，项目太多忙不过来。

**Comment by MrShenf** [comment]
> 肯定会更新的，目前做了接收跟转发的，有时间就会搞，项目太多忙不过来。

请问这个项目还更新吗，目前的代码里面有实现转发中心的逻辑吗

**Comment by SmallChi** [comment]
> > 肯定会更新的，目前做了接收跟转发的，有时间就会搞，项目太多忙不过来。
> 
> 请问这个项目还更新吗，目前的代码里面有实现转发中心的逻辑吗

转发只实现定位的转发。
