### ISSUE TITLE
每天8000w数据存储

### ISSUE THREAD

**Issue by myFirstway** [SmallChi/JT809DotNetty#2]
每天8000w数据，一个月就24亿，主从模式可以承受的住吗？

**Comment by SmallChi** [comment]
可以。

**Comment by myFirstway** [comment]
> 可以。
能分享下具体解决方案吗？单表数据多少？数据库服务器配置

**Comment by SmallChi** [comment]
时间有点久了，不太记得了，服务器配置倒是知道：两台物理机8c16g的pgsql,7200的硬盘，好像是4t，按天存储按hash分64个区。

**Comment by myFirstway** [comment]
> 时间有点久了，不太记得了，服务器配置倒是知道：两台物理机8c16g的pgsql,7200的硬盘，好像是4t，按天存储按hash分64个区。

谢谢啊
