### ISSUE TITLE
链路管理

### ISSUE THREAD

**Issue by zuohuaijun** [SmallChi/JT809DotNetty#3]
809协议里面的链路是不是就是一个socket连接啊？根据请求方的请求信息，如果正确，服务端就建立一个标识的连接，如果不正确就断开，这样理解正确么？老大 问下   咱这个框架是单独于supersocket么？ 还会继续更新么？谢谢

**Comment by SmallChi** [comment]
是的，可以这么理解，可以用supersocket这个项目，809估计要到明年才会开始动工，现在主要是完善808和1078。
