### ISSUE TITLE
.Net Framework该如何引用JT809DotNetty

### ISSUE THREAD

**Issue by zuohuaijun** [SmallChi/JT809DotNetty#4]
我想用先前创建.Net Framework supersocket框架（包括websocket转发）引用JT809DotNetty可行么？请指教简单的调用的用法，该怎么初始化JT809DotNetty呢   谢谢

**Comment by zuohuaijun** [comment]
主要是如何JT809CoreDotnettyExtensions.AddJT809SuperiorPlatform调用，主链路为服务端、从链路为客户端   谢谢 求指点

**Comment by SmallChi** [comment]
直接netcore不就好了。。额   这里面JT809.DotNetty.Simples不是有demo   直接启动就可以运行了，或者加我qq晚上的时候给你看看怎么运行。
